In [2]:
import pandas as pd

In [4]:
dump = pd.read_csv("Dagster/datasets/datadump.csv")

In [7]:
dump['Age'].unique()

array(['35 - 39', '25 - 29', '40 - 49', '30 - 34', '50 - 59', '18 - 24',
       'Below 18', '60+'], dtype=object)

In [8]:
dump.describe(include='all')

,ID,Sector,Overall Satisfaction with Customer Service in Sector,Companies with Which Business Was Conducted in the Last 12 Months,Company Interacted with Most Often,Trust (Extent of Satisfaction),Professionalism (Extent of Satisfaction),"Branches, Branding & Outlook (Extent of Satisfaction)",Competence (Extent of Satisfaction),Ease of Doing Business (Extent of Satisfaction),...,Likely to Recommend,Means of Interaction,Channels of Interaction,Gender,Age,Region,Highest Education,Income,Nationality,Awareness of Survey
count,21393.000000,21393.000000,21393.000000,21393,21387,21393.000000,21393.000000,21393.000000,21393.000000,21393.000000,...,21393.000000,21393,21393,21393,21393,21178,21393,21393,21393,20077
unique,NaN,NaN,NaN,3763,1683,NaN,NaN,NaN,NaN,NaN,...,NaN,3,1089,2,8,40,7,14,2,1083
top,NaN,NaN,NaN,"MOBILE TELECOMMUNICATIONS NETWORK (MTN) ,",MOBILE TELECOMMUNICATIONS NETWORK (MTN),NaN,NaN,NaN,NaN,NaN,...,NaN,Both Digital and Traditional Channels,"In Person,",Female,30 - 34,Lagos,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N100,000 - N150,000",Nigerian,Via Whatsapp Group
freq,NaN,NaN,NaN,1084,1544,NaN,NaN,NaN,NaN,NaN,...,NaN,8898,7474,14898,6654,9899,16276,3814,21312,1061
mean,18485.307344,95.655822,4.630720,NaN,NaN,4.567569,4.603141,4.503108,4.480905,4.496611,...,5.920395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,6178.078561,221.677632,1.558638,NaN,NaN,1.659927,1.653099,1.607819,1.617969,1.601350,...,2.835454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,7784.000000,1.000000,1.000000,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,13136.000000,2.000000,4.000000,NaN,NaN,4.000000,4.000000,4.000000,3.000000,4.000000,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,18485.000000,5.000000,5.000000,NaN,NaN,5.000000,5.000000,5.000000,5.000000,5.000000,...,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,23836.000000,8.000000,6.000000,NaN,NaN,6.000000,6.000000,6.000000,6.000000,6.000000,...,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,29182.000000,634.000000,7.000000,NaN,NaN,7.000000,7.000000,7.000000,7.000000,7.000000,...,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dump.head(10)

,ID,Sector,Overall Satisfaction with Customer Service in Sector,Companies with Which Business Was Conducted in the Last 12 Months,Company Interacted with Most Often,Trust (Extent of Satisfaction),Professionalism (Extent of Satisfaction),"Branches, Branding & Outlook (Extent of Satisfaction)",Competence (Extent of Satisfaction),Ease of Doing Business (Extent of Satisfaction),...,Likely to Recommend,Means of Interaction,Channels of Interaction,Gender,Age,Region,Highest Education,Income,Nationality,Awareness of Survey
0,7784,2,2,"Globalcom Limited,",Globalcom Limited,3,2,3,3,3,...,2,Both Digital and Traditional Channels,"In Writing,Website,In Person,",Male,35 - 39,Edo,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N151,000 - N199,000",Nigerian,Agbonta Daniel Ojieh
1,7785,2,5,"9mobile,",9mobile,7,3,7,3,4,...,2,Traditional Channels,"In Person,",Male,25 - 29,Abuja,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N41,000 - N60,000",Nigerian,Agnes Okoh
2,27553,1,1,"ACCESS ARM PENSIONS,",ACCESS ARM PENSIONS,1,1,1,1,1,...,0,Both Digital and Traditional Channels,"Mobile App,In Person,In Writing,Email,Text/Ove...",Male,40 - 49,Gombe,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N300,000 - N500,000",Nigerian,JY202748
3,7812,1,2,"ACCESS BANK,",ACCESS BANK,2,1,3,1,2,...,1,Both Digital and Traditional Channels,"Mobile App,Text/Over the Phone,",Female,40 - 49,NaN,"Masters, Professorial, Doctorate, Professional...","N200,000 - N300,000",Nigerian,Via My Organization
4,7864,1,5,"ACCESS BANK,",ACCESS BANK,4,4,4,4,3,...,3,Digital Channels,"Social Media,",Female,35 - 39,Lagos,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N300,000 - N500,000",Nigerian,Via My Organization
5,7927,1,5,"ACCESS BANK,",ACCESS BANK,6,5,5,5,4,...,6,Both Digital and Traditional Channels,"Text/Over the Phone,In Person,",Female,25 - 29,Abuja,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N100,000 - N150,000",Nigerian,PJ0034
6,7969,1,5,"ACCESS BANK,",ACCESS BANK,6,6,5,6,7,...,9,Both Digital and Traditional Channels,"Email,Social Media,In Person,Mobile App,",Female,30 - 34,Abuja,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N300,000 - N500,000",Nigerian,WAACSP ECOWAS
7,7972,1,7,"ACCESS BANK,",ACCESS BANK,7,7,6,6,5,...,8,Both Digital and Traditional Channels,"Mobile App,Email,In Person,Social Media,",Female,30 - 34,Abuja,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N300,000 - N500,000",Nigerian,EU0044
8,8007,1,5,"ACCESS BANK,",ACCESS BANK,5,5,5,5,5,...,3,Both Digital and Traditional Channels,"Text/Over the Phone,In Person,",Female,40 - 49,Lagos,"Masters, Professorial, Doctorate, Professional...","N300,000 - N500,000",Nigerian,TR0023
9,8124,1,6,"ACCESS BANK,",ACCESS BANK,5,5,5,5,5,...,6,Both Digital and Traditional Channels,"In Person,",Female,25 - 29,Bayelsa,University (BSc/BA/B.Ed) Or Polytechnic (HND) ...,"N151,000 - N199,000",Nigerian,NaN

In [10]:
dump.isnull().sum()

ID                                                                      0
Sector                                                                  0
Overall Satisfaction with Customer Service in Sector                    0
Companies with Which Business Was Conducted in the Last 12 Months       0
Company Interacted with Most Often                                      6
Trust (Extent of Satisfaction)                                          0
Professionalism (Extent of Satisfaction)                                0
Branches, Branding & Outlook (Extent of Satisfaction)                   0
Competence (Extent of Satisfaction)                                     0
Ease of Doing Business (Extent of Satisfaction)                         0
Processes and Procedures (Extent of Satisfaction)                       0
Customer-focused Innovations (Extent of Satisfaction)                   0
Engagement with Customers (Extent of Satisfaction)                   4334
Order of Importance (OOI) - Trust                                       0
Order of Importance (OOI) - Professionalism                             0
Order of Importance (OOI) - Branches, Branding & Outlook                0
Order of Importance (OOI) - Competence                                  0
Order of Importance (OOI) - Ease of Doing Business                      0
Order of Importance (OOI) - Processes and Procedures                    0
Order of Importance (OOI) - Customer-focused Innovations                0
Order of Importance (OOI) - Engagement with Customers                   0
Impressions on Customer Service                                        60
Preference of Service                                                   0
Satisfied/Dissatisfied                                                  0
Likely to Recommend                                                     0
Means of Interaction                                                    0
Channels of Interaction                                                 0
Gender                                                                  0
Age                                                                     0
Region                                                                215
Highest Education                                                       0
Income                                                                  0
Nationality                                                             0
Awareness of Survey                                                  1316
dtype: int64

In [12]:
len(dump)

21393